#!/bin/bash
# Script that sanitizes the output generated by Regenerator
strings=(
        a0014
        a0019
        a001A
        a0022
        a0023
        a0024
        a0025
        a0026
        a0027
        a0028
        a0029
        a002A
        a002B
        a003D
        a003F
        a0041
        a004B
        a004E
        a0053
        a0054
        a0055
        a0056
        a0057
        a0058
        a0059
        a005A
        a00A7
        a00A8
        a00C9
        a00D7
        a00F7
        a00F8
        a00FB
        a00FC
        a00FD
        a00FE
        f0000
        f004B
        f004C
        f00A2
        )

for val in "${strings[@]}"; do
        echo ${val}
        sed -i "s/~${val}/${val},b/g" co1.tas
done

sed -i "s/ASL $/ASL A/g" co1.tas
sed -i "s/ROL $/ROL A/g" co1.tas
sed -i "s/LSR $/LSR A/g" co1.tas
sed -i "s/LSL $/LSL A/g" co1.tas
